name: base
channels:
- defaults
- conda-forge
dependencies:
- nodejs
#- six #=1.11.0
# core packages
- pip
- nbdime
# code audit
- watermark
- pylint
- pytest
- autopep8
- pep8
- pylama
- flake8
- black
#jupyter lab
- jupyter
- jupyterlab
- ipykernel
- notebook
#- nb_conda
- nb_conda_kernels
#- jupyter_nbextensions_configurator
#- jupyter_contrib_nbextensions
- jupyterlab-git
- jupyterlab_code_formatter
- pip:
    - jupyterlab_latex