name: env_nlp_text_class
channels:
- defaults
- conda-forge
- districtdatalabs
- plotly
dependencies:
- python=3.6.9
- ipykernel=5.1.2
- pip=19.2.3
- numpy=1.17.2
- pandas=0.25.1
- pymongo=3.8.0
- plotly=4.1.0
- chart-studio =1.0.0
- graphviz=2.38.0
- seaborn=0.9.0
- wordcloud=1.5.0
- pydot=1.4.1
- scipy=1.3.1
- statsmodels=0.10.1
- catboost=0.16.5
- lightgbm=2.2.3
- scikit-mdr=0.4.4
- skrebate=0.6
- tpot=0.10.2
- yellowbrick=0.9.1
- lime=0.1.1.36
- scikit-learn=0.21.3
- scikit-plot=0.3.7
- scikit-optimize=0.5.2
- nltk=3.4.4
- gensim=3.7.3
- spacy=2.1.8
- langdetect=1.0.7
- watermark=1.8.2
- pylint=2.3.1
- pytest=5.1.1
- autopep8=1.4.4
- pep8=1.7.1
- pylama=7.7.1
- bayesian-optimization=1.0.1
- google-cloud-storage=1.19.0
- google-cloud-bigquery=1.19.0
- google-auth=1.6.3
- google-api-core=1.14.2
- google-api-python-client=1.7.11
- google-auth-httplib2=0.0.3
- google-cloud-core=1.0.3
- google-cloud-datastore=1.9.0
- google-cloud-language=1.3.0
- google-cloud-spanner=1.9.0
- google-cloud-translate=1.6.0
- google-cloud-vision=0.38.1
- google-pasta=0.1.7
- google-resumable-media=0.3.3
- googleapis-common-protos=1.6.0
- tensorflow-hub=0.6.0
- tensorflow-datasets=1.2.0
- pip:
  - tensorflow==2.0.0
  - tensorflow-addons==0.5.2
  - tensorflow-text==1.0.0b2
  - tf-explain==0.0.2a0
  - tfx==0.14.0
  - xgboost==0.90
  - apache-beam[gcp]
  - google-cloud-dlp==0.12.1
  - google-cloud-pubsub==1.0.0
  - google-cloud-videointelligence==1.11.0
  - google-cloud-logging==1.12.1
  #- “git+https://github.com/tarrade/cutter-ng.git#egg=cutter-ng”
  #- “https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz#egg=en_core_web_sm==2.1.0"
  #- “https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.1.0/en_core_web_md-2.1.0.tar.gz#egg=en_core_web_md==2.1.0”
  #- “https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-2.1.0/en_core_web_lg-2.1.0.tar.gz#egg=en_core_web_lg==2.1.0"
  #- “https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.1.0/de_core_news_sm-2.1.0.tar.gz#egg=de_core_news_sm==2.1.0”
  #- “https://github.com/explosion/spacy-models/releases/download/fr_core_news_sm-2.1.0/fr_core_news_sm-2.1.0.tar.gz#egg=fr_core_news_sm==2.1.0"
  #- “https://github.com/explosion/spacy-models/releases/download/it_core_news_sm-2.1.0/it_core_news_sm-2.1.0.tar.gz#egg=it_core_news_sm==2.1.0”

